---
source_1:
  id: 102215
  slug: haiyore-nyaruko-san
  title_en: Haiyore! Nyaruko-san (Series)
  title_jp: "這いよれ! ニャル子さん"
  title_romaji: Haiyore! Nyarukosan
  title_furigana: "はいよれ! ニャルこさん"
  anime_db_id: 102215
source_2:
  id: 1693
  slug: yosuga-no-sora
  title_en: Yosuga no Sora
  title_jp: "ヨスガノソラ"
  title_romaji: Yosuga no Sora
  title_furigana: "よすがのそら"
  anime_db_id: 1693
source_3:
  id: 2143
  slug: osananajimi-wa-daitouryou-my-girlfriend-is-the-president
  title_en: Osananajimi wa Daitouryou ~My girlfriend is the President.~
  title_jp: "幼なじみは大統領 My girlfriend is the PRESIDENT."
  title_romaji: Osananajimi wa Daitouryou ~Mai  Gaarufurendo izu za Purejidento.~
  title_furigana: "おさななじみはだいとうりょう マイ・ガールフレンド・イズ・ザ・プレジデント"
  anime_db_id: 2143
source_4:
  id: 103317
  slug: love-live-school-idol-project
  title_en: Love Live! School Idol Project
  title_jp: "ラブライブ！ School idol project"
  title_romaji: Rabu Raibu! School Idol Project!
  title_furigana: "ラブライブ！ スクールアイドルプロジェクト!"
  anime_db_id: 103317
source_5:
  id: 2552
  slug: puella-magi-madoka-magica
  title_en: Puella Magi Madoka Magica
  title_jp: "魔法少女まどか☆マギカ"
  title_romaji: Mahou Shoujo Madoka ★ Magika
  title_furigana: "まほうしょうじょまどかマギカ"
  anime_db_id: 2552
source_6:
  id: 104289
  slug: the-idolmaster
  title_en: The Idolmaster
  title_jp: THE iDOLM@STER
  title_romaji: Aidoru Masutaa
  title_furigana: "アイドルマスター"
  anime_db_id: 104289
source_7:
  id: 104217
  slug: saekano-how-to-raise-a-boring-girlfriend
  title_en: 'Saekano: How to Raise a Boring Girlfriend'
  title_jp: "冴えない彼女(ヒロイン)の育てかた"
  title_romaji: Saenai Heroine no Sodatekata
  title_furigana: "さえないヒロインのそだてかた / 冴えカノ"
  anime_db_id: 104217
