#!/bin/bash

# copy from "bundle exec rake secret"
export SECRET_KEY_BASE="GENERATE-SECRET"

export TWITTER_APP_KEY="CREATE-TWITTER-APP"
export TWITTER_APP_SECRET="CREATE-TWITTER-APP"

export TWITTER_ACCESS_TOKEN="ADMIN-TOKEN"
export TWITTER_ACCESS_TOKEN_SECRET="ADMIN-TOKEN-SECRET"

