#!/bin/bash

export TWITTER_APP_KEY="CREATE-TWITTER-APP"
export TWITTER_APP_SECRET="CREATE-TWITTER-APP"

export TWITTER_ACCESS_TOKEN="ADMIN-TOKEN"
export TWITTER_ACCESS_TOKEN_SECRET="ADMIN-TOKEN-SECRET"

