# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3431e2ecd4308960556b2543d1272182123a0d585d04ee05063eb99270e842850ef8007037b7a4abfb3c4df9dcbffee9d7d480035eab3a050282eb1f2be0772f
  user: admin
  password: asdf1234

test:
  secret_key_base: 608c8f2c8519964d3d5c9478873b837ee019023cd93582e37ae51d606b3d0a876b7c9cce95f8a6b928ec58875a7a96228509aaab0220c8de5235a2ccda5e3052
  user: admin
  password: asdf1234

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  user: admin
  password: <%= ENV["ADMIN_PASSWORD"] %>
  
