production:
  twitter_app_key: "<%= ENV['TWITTER_APP_KEY'] %>"
  twitter_app_secret: "<%= ENV['TWITTER_APP_SECRET'] %>"

development:
  twitter_app_key: "oNQNCxQaBIm973t8L9YNrlas5"
  twitter_app_secret: "Tcq2XKB2ChSKoratA6AFLovdVZfltA406CD8lGdr3ZtV3h40uJ"

test:
  twitter_app_key: "dummy-twitter-app-key"
  twitter_app_secret: "dummy-twitter-app-secret"

